name: "Copy built website"

on:
  push:
    branches: ["master"]
    paths:
      - "_site/**"

jobs:
  copy-site:
    name: "Copy built site"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: "Update gh-pages"
        run: |
          git clone https://github.com/$GITHUB_REPOSITORY.git --branch gh-pages --single-branch gh-pages
          ls
          cp -r ./_site/* gh-pages/
          cd gh-pages
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update gh-pages" -a || true

      - name: "Push gh-pages"
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
